# Generated by Django 5.1.3 on 2024-11-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/images/')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviews', models.PositiveBigIntegerField()),
                ('start_date', models.DateField()),
                ('time', models.CharField(max_length=255)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
